workflows:
  react-native-android:
    name: AFRA Booking Android
    max_build_duration: 60
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Install EAS CLI
        script: npm install -g eas-cli
      - name: Expo Prebuild
        script: npx expo prebuild --platform android --clean --no-install
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease -x bundleReleaseJsAndAssets
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
